import type { CatalogEvent } from "@/features/catalog/catalog.types";

export const mockCatalog: CatalogEvent[] = [
  {
    id: "event-001",
    slug: "frequencia-urbana",
    title: "Frequência Urbana",
    summary: "Três palcos e uma noite inteira dedicada à nova música brasileira.",
    category: "Shows e festivais",
    city: "São Paulo",
    venue: "Complexo Barra Funda",
    dateLabel: "22 AGO · 19h",
    startsAt: "2026-08-22T19:00:00-03:00",
    priceLabel: "a partir de R$ 90",
    imageUrl: "/images/events/concert-hero.webp",
    imageAlt: "Público diante de um grande palco iluminado durante um show noturno",
    featured: true,
  },
  {
    id: "event-002",
    slug: "pulso-eletrico",
    title: "Pulso Elétrico",
    summary: "Uma celebração audiovisual com artistas independentes e convidados.",
    category: "Shows e festivais",
    city: "Rio de Janeiro",
    venue: "Marina da Glória",
    dateLabel: "29 AGO · 18h",
    startsAt: "2026-08-29T18:00:00-03:00",
    priceLabel: "a partir de R$ 110",
    imageUrl: "/images/events/concert-hero.webp",
    imageAlt: "Festival ao ar livre com luzes azuis e público animado",
    featured: true,
  },
  {
    id: "event-003",
    slug: "sabores-do-brasil",
    title: "Sabores do Brasil",
    summary: "Cozinhas regionais, música e encontros ao redor de grandes mesas.",
    category: "Experiências",
    city: "São Paulo",
    venue: "Parque Villa-Lobos",
    dateLabel: "05 SET · 11h",
    startsAt: "2026-09-05T11:00:00-03:00",
    priceLabel: "a partir de R$ 45",
    imageUrl: "/images/events/gastronomy.webp",
    imageAlt: "Festival gastronômico ao ar livre durante o pôr do sol",
    featured: true,
  },
  {
    id: "event-004",
    slug: "mesa-aberta",
    title: "Mesa Aberta",
    summary: "Chefs convidados apresentam menus curtos em uma tarde descontraída.",
    category: "Experiências",
    city: "Belo Horizonte",
    venue: "Praça da Liberdade",
    dateLabel: "12 SET · 12h",
    startsAt: "2026-09-12T12:00:00-03:00",
    priceLabel: "a partir de R$ 35",
    imageUrl: "/images/events/gastronomy.webp",
    imageAlt: "Pessoas compartilhando pratos em um encontro gastronômico",
    featured: false,
  },
  {
    id: "event-005",
    slug: "a-cidade-que-ficou",
    title: "A Cidade que Ficou",
    summary: "Uma montagem sobre memória, encontros e as rotas que escolhemos.",
    category: "Teatro",
    city: "São Paulo",
    venue: "Teatro Oficina",
    dateLabel: "18 SET · 20h",
    startsAt: "2026-09-18T20:00:00-03:00",
    priceLabel: "a partir de R$ 55",
    imageUrl: "/images/events/theatre.webp",
    imageAlt: "Dois atores em cena sob luzes azuis e corais",
    featured: false,
  },
  {
    id: "event-006",
    slug: "entrelinhas",
    title: "Entrelinhas",
    summary: "Dança e teatro se encontram em uma narrativa sem palavras.",
    category: "Teatro",
    city: "Curitiba",
    venue: "Teatro Guaíra",
    dateLabel: "26 SET · 20h30",
    startsAt: "2026-09-26T20:30:00-03:00",
    priceLabel: "a partir de R$ 60",
    imageUrl: "/images/events/theatre.webp",
    imageAlt: "Performance contemporânea em um palco de iluminação dramática",
    featured: false,
  },
  {
    id: "event-007",
    slug: "quase-pontual",
    title: "Quase Pontual",
    summary: "Novos nomes da comédia dividem o palco em uma sessão única.",
    category: "Comédia",
    city: "São Paulo",
    venue: "Teatro das Artes",
    dateLabel: "02 OUT · 21h",
    startsAt: "2026-10-02T21:00:00-03:00",
    priceLabel: "a partir de R$ 48",
    imageUrl: "/images/events/comedy.webp",
    imageAlt: "Comediante se apresentando em um palco intimista",
    featured: false,
  },
  {
    id: "event-008",
    slug: "rir-de-nos-mesmos",
    title: "Rir de Nós Mesmos",
    summary: "Observações sobre trabalho, família e a vida nas grandes cidades.",
    category: "Comédia",
    city: "Campinas",
    venue: "Teatro Iguatemi",
    dateLabel: "10 OUT · 20h",
    startsAt: "2026-10-10T20:00:00-03:00",
    priceLabel: "a partir de R$ 42",
    imageUrl: "/images/events/comedy.webp",
    imageAlt: "Show de comédia com público e iluminação em tons quentes",
    featured: false,
  },
];
